### ISSUE TITLE
Kein Textanker

### ISSUE THREAD

**Issue by CeeK4y** [tuc0w/COVID-19-Inzidenz-Widget#1]
Sieht gut aus. 
Leider verrückt der Text aber je nach Widget-Größe außerhalb ( oberhalb, unterhalb und links) des schwarzen Hintergrunds.

**Comment by CeeK4y** [comment]
![Screenshot_20201024-084843](https://user-images.githubusercontent.com/73369878/97070087-cf981500-15d5-11eb-99a4-aeeac105a206.jpg)

**Comment by tuc0w** [comment]
Danke :)

Kannst du mir beschreiben wie es genau dazu gekommen ist? Hast du ein 2x4 Widget oder ein kleineres/größeres angelegt und dann verkleinert/vergrößert?

**Comment by CeeK4y** [comment]
Der Fehler Tripp bereits in der KWGT App auf wenn ich das 2x4 Widget gewählt habe.
![Screenshot_20201024-155746](https://user-images.githubusercontent.com/73369878/97083646-c036bd00-1611-11eb-8ae8-c5feac1cb415.jpg)



Ich habe es nun für mich einlösen können, dass ich die einzelnen Textpositionen und den Hintergrund manuell verschoben und angepasst habe.

Der fehler tritt in beiden App Versionen Lite und paid Version von KWGT auf, zudem sowohl im preset als auch im backup.

**Comment by tuc0w** [comment]
Hey, danke für deine Rückmeldung! 

Kannst du mir sagen was dein Homescreen für ein Layout hat? Bei mir sind es 5x6 (5 Icons pro Reihe) und ich habe es vorhin auf einem Device mit 4 Icons pro Reihe getestet und konnte dort den Fehler nachstellen.

**Comment by CeeK4y** [comment]
6 Reihen, 5 Icons pro Reihe. So ist es auch bei mir.

Wie gesagt, das passiert bereits beim Import der Datei unabhängig davon, welches Widget Layout ich wähle. 

Ich vermute, dass es an der Kustom App liegt. Dort passiert es auch sporadisch, dass mein gespeichertes Layout, welches ich meinem Homescreen angepasst habe, seine Ausrichtung und Positionen resettet.

**Comment by tuc0w** [comment]
Habe mehrfach versucht es zu reproduzieren, hat leider nur 1x geklappt und wie du schon vermutest liegt es vermutlich an der Kustom App daher schließe ich das Issue.
